version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - base
      - redis
    links:
      - base
      - redis
  redis:
    image: "redis:alpine"
  base:
    image: mysql
    container_name: mysqlnew1
    ports:
      - "3309:3306"
    environment:
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=root 
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=example_schema